

/*******************************
  Crossfire
********************************/
typedef enum {
    TELEM_CRSF_RX_RSSI1 = 1,
    TELEM_CRSF_RX_RSSI2,
    TELEM_CRSF_RX_QUALITY,
    TELEM_CRSF_RX_SNR,
    TELEM_CRSF_RX_ANTENNA,
    TELEM_CRSF_RF_MODE,
    TELEM_CRSF_TX_POWER,
    TELEM_CRSF_TX_RSSI,
    TELEM_CRSF_TX_QUALITY,
    TELEM_CRSF_TX_SNR,
    TELEM_CRSF_BATT_VOLTAGE,
    TELEM_CRSF_BATT_CURRENT,
    TELEM_CRSF_BATT_CAPACITY,
    TELEM_CRSF_GPS_LATITUDE,
    TELEM_CRSF_GPS_LONGITUDE,
    TELEM_CRSF_GPS_GROUND_SPEED,
    TELEM_CRSF_GPS_HEADING,
    TELEM_CRSF_GPS_ALTITUDE,
    TELEM_CRSF_GPS_SATELLITES,
    TELEM_CRSF_ATTITUDE_PITCH,
    TELEM_CRSF_ATTITUDE_ROLL,
    TELEM_CRSF_ATTITUDE_YAW,
    TELEM_CRSF_FLIGHT_MODE,
    TELEM_CRSF_LAST
} crossfire_telem_t;
